### PR TITLE
Vite

### PR DESCRIPTION
**Pull request by c4lyp5o**

### CODE REVIEW

**Comment by CyferShepard** [comment]
Hey @c4lyp5o , just checked it out, its amazing how fast this builds and I'm seriously impressed.

Just a few things I noticed however, it seems some assets are missing like the Jellystat Icon for example, some styles don't load or have weird color issues and I also see that image resources aren't being loaded (I'm checking the network calls and it seems to be an issue with how its being proxied when its trying to retrieve the images from the proxy epi endpoint). 

Im not really familiar with how vite works so i was hoping you can sort those out,

**Comment by c4lyp5o** [comment]
Thank you for checking it out @CyferShepard. Yeah, i was amazed too at the speed of vite. Its definitely a boost. I will work on the issues as soon as i can. I'll ping you when its done.

**Comment by c4lyp5o** [comment]
Hi @CyferShepard. Ive added some changes for you to evaluate. The problem with the font is remedied by making the global font color white. Ive also made some housekeeping.

**Comment by CyferShepard** [comment]
Hey @c4lyp5o , just had a quick look and all seems good, fixed a minor issue where vite proxies are case sensitive so some api calls for images where calling ```Proxy``` instead of ```proxy``` causing images to fail to load. Will test more in-depth by the end of the day when im back from work.

**Comment by c4lyp5o** [comment]
@CyferShepard oh yeah, i noticed that too about the /Proxy api call but since its on the backend, i thought its better if you take charge of it. but really glad to hear that everything is working fine. ive also modified the docker build process. my testing shows its working as it should. maybe you could take a second look if there is anything amiss. thank you again.

**Comment by CyferShepard** [comment]
hey @c4lyp5o , will do, i attempted to make a few test builds last night but was having issues, simple stuff like which run command it was trying to execute (it was just starting the server and not the front end) plus a weird bug where the built version just returns a white page(this seems to be more of a react issue as i tested with the old build and had the same issue). Once iv got it successfully built il merge to unstable

**Comment by CyferShepard** [comment]
Hey @c4lyp5o , i just had to make some changes, it looks like everything is in working order, i just was having issues where image kept failing to build when it was running the ```npm build``` part. i reverted the Dockerfile and now that seems to have done the trick. im not sure if you want to take a look at it and see if you could get your Dockerfile  to work or if your happy with it as is so i can merge whenever your ready.

**Comment by c4lyp5o** [comment]
@CyferShepard hi cyfer. thanks for reviewing. i think we might be missing 'npm run build' in the package.json? because vite has to build the static html first.

the code now is 
`"start": "cd backend && node server.js"`

i think it should be
`"start": "npm run build && cd backend && node server.js"`

what do you think?

**Comment by CyferShepard** [comment]
So it actually builds it first when the container is being built so itl have the static files when the container is created. if you add build itl rebuild the static files every time the container is run which seems wastefull

**Comment by c4lyp5o** [comment]
@CyferShepard hi cyfer. sorry for my late reply. holidays around my parts. i see, now that you explained it. i have reverted my last commit and i think it is ready to be merged. thank you.

**Comment by CyferShepard** [comment]
hey @c4lyp5o , its cool, i also got abit busy this weekend, there's a few merge conflicts, youl need to resolve those on your branch before i can merge to unstable on my side

**Comment by c4lyp5o** [comment]
@CyferShepard hi cyfer. i synced the branches. i think we can merge now

**Pull request merged**
