### PR TITLE
Feature/geolocate ip

### PR DESCRIPTION
**Pull request by DaftFuzz**
From [this](https://github.com/CyferShepard/Jellystat/issues/117) feature request. 

- Added new API route `utils/geolocateIp`. This calls the Maxmind API using env variables for authentication to return geolocation data for a given IP address
- IP Address is displayed in the session card, and is clickable. On click, opens a modal and makes call to the new API endpoint, displays some basic geolocation info

image

### CODE REVIEW

**Comment by CyferShepard** [comment]
Hey @DaftFuzz , im having some issues testing this build, can you help me with this, i created an account on maxmind, got my api key and account id, set all those up, but i get a Error Bad Request Response. is there any additional setup that needs to be done?

**Comment by DaftFuzz** [comment]
Hey, so the account ID is set up as `GEOLITE_ACCOUNT_ID` env variable, and api key as `GEOLITE_LICENSE_KEY`? At what point are you getting the Bad Request response? From the geolite API, or from the frontend?

**Comment by CyferShepard** [comment]
Okay so managed to find then issue, the option to trace the ip is still available for local/private ips. but when its sent through the API its rejected as ``` data: {
      code: 'IP_ADDRESS_RESERVED',
      error: "The IP address 'xxx.xxx.xxx.xxx' is a reserved IP address (private, multicast, etc.)."
    }```. So youl probably need to add a check for this to make the IP non clickable if its a private/lan IP. Also to prevent some confusion can you add a check in the frontend to see if these ENVs are set, if they are not, the user shouldn't be able to open up the modal

**Comment by DaftFuzz** [comment]
Ah, gotcha, yeah I did my testing with remote IPs only so missed that. Will make those changes 👍

**Comment by CyferShepard** [comment]
Looks all good on my side for now @DaftFuzz besides the 1 small change i added

**Pull request merged**
